name = "mova-agent-api-v0"
account_id = "1a59aedce21bfac94cb0f6c8b2da0484"
main = "build/worker/shim.mjs"
compatibility_date = "2026-05-23"
workers_dev = true

[build]
command = "worker-build --release --features worker"

[[kv_namespaces]]
binding = "MOVA_RUN_STORE"
id = "a276a02220fd43ff938eb4ff6b82e0a7"

[vars]
MOVA_WEBHOOK_SITE_ALLOWED_URL = "https://webhook.site/91c77fd2-f847-43ed-9c18-79b5aebc8b95"
